services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.v1
    image: dc-api:v1
    environment:
      - PORT=3000
    ports:
      - "5000:3000"
    restart: unless-stopped

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./openapi:/openapi:ro
    restart: unless-stopped
